# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('published_at', models.DateTimeField()),
                ('thumbnails_default', models.URLField()),
                ('thumbnails_medium', models.URLField()),
                ('thumbnails_high', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
