# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='comment_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='subscriber_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='video_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='view_count',
            field=models.IntegerField(null=True),
        ),
    ]
